version: 2.1
jobs:
  build: 
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install flake8
            flake8 --exclude=venv* --statistics
