version: 2.1
jobs:
  build: 
    docker:
      - image: circleci/python:latest
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install flake8
            flake8 --exclude=venv*,LICENSE,README.md --statistic project/* --output-file=test-results/flake8/flake8.xml
      
      - store_test_results:
          path: test-results
